name: Ship Time Update

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  update_ship_time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install timezonefinder pytz requests colorama

      - name: Run Python script
        run: python shiptime.py > output.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ship_output
          path: output.txt
