name: Get Vessel Local Time and Update README (Every 30 mins and on Push)

on:
  # Run every 30 mins
  schedule:
    # Cron syntax for every 30 mins: "* */30 *"
    cron: "* */30 *"
  # Run on push to main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: pip install requests pytz timezonefinder colorama
      - name: Run the script
        run: python shiptime.py | tee output.txt
      - name: Get Local Time
        run: |
          local_time=$(cat output.txt | grep Local\ Time: | cut -d ':' -f 2-)
          echo "Local Time: $local_time"
      - name: Update README.md (Only on push)
        if: github.event_name == 'push'
        run: |
          echo "**Local Time:** $local_time" >> README.md
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with local vessel time: $local_time"
          git push origin main
